In [ ]:
#spacy, textblob, nltk
#https://radimrehurek.com/gensim/auto_examples/index.html
import gensim

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
model=KeyedVectors.load_word2vec_format("/content/drive/MyDrive/GoogleNews-vectors-negative300.bin.gz",binary=True,limit=500000)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
model

In [ ]:
model["cricket"]

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [ ]:
len(model["cricket"])

300

In [ ]:
model["space"]

array([-0.11914062,  0.078125  ,  0.05566406, -0.06542969, -0.11523438,
       -0.19726562,  0.07373047, -0.03112793,  0.03930664, -0.13769531,
       -0.04833984, -0.06542969, -0.12304688, -0.14941406, -0.04467773,
       -0.06494141,  0.06542969,  0.11621094,  0.15820312,  0.09179688,
       -0.01409912, -0.14941406, -0.12255859, -0.01843262, -0.1015625 ,
        0.29101562, -0.05297852, -0.05981445,  0.0168457 , -0.25195312,
       -0.26171875, -0.01965332,  0.03662109, -0.0007782 , -0.06640625,
       -0.34960938,  0.03735352,  0.02502441,  0.00668335, -0.07177734,
       -0.10546875, -0.10351562,  0.19140625,  0.4296875 , -0.07080078,
       -0.05615234, -0.09082031,  0.203125  ,  0.06787109, -0.14355469,
        0.08935547, -0.09619141, -0.19726562, -0.16992188, -0.18164062,
       -0.15332031,  0.13769531, -0.08447266,  0.24121094, -0.02124023,
        0.08398438, -0.13574219, -0.05834961, -0.28710938, -0.23144531,
        0.03759766, -0.01611328, -0.078125  , -0.11132812,  0.18

In [ ]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035123825073)]

In [ ]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
model.most_similar("sunny")

[('balmy', 0.7314587831497192),
 ('sunshine', 0.7251086831092834),
 ('overcast', 0.6918097734451294),
 ('breezy', 0.6885849237442017),
 ('gloriously_sunny', 0.6779158711433411),
 ('sunny_skies', 0.6688455939292908),
 ('chilly', 0.66850346326828),
 ('windy', 0.6603769659996033),
 ('drizzly', 0.6585174202919006),
 ('sun_drenched', 0.6578938364982605)]

In [ ]:
model.most_similar("facebook")

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [ ]:
model.similarity('man','woman')

0.76640123

In [ ]:
model.similarity('man','java')

0.019312028

In [ ]:
model.similarity('man','python')

0.2097966

In [ ]:
model.similarity('man','php')

0.008337109

In [ ]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [ ]:
model["woman"]

array([ 2.43164062e-01, -7.71484375e-02, -1.03027344e-01, -1.07421875e-01,
        1.18164062e-01, -1.07421875e-01, -1.14257812e-01,  2.56347656e-02,
        1.11816406e-01,  4.85839844e-02, -9.71679688e-02, -3.43750000e-01,
       -6.29882812e-02, -1.25000000e-01, -2.70996094e-02,  9.42382812e-02,
       -1.87500000e-01, -5.34667969e-02,  6.25000000e-02, -3.05175781e-02,
       -2.90527344e-02, -4.80957031e-02, -5.51757812e-02, -4.08203125e-01,
        1.01318359e-02, -2.32421875e-01, -1.70898438e-01,  2.63671875e-01,
        3.49609375e-01, -2.11914062e-01,  1.43554688e-01, -6.22558594e-03,
       -2.25585938e-01, -1.05468750e-01, -1.16210938e-01,  1.23046875e-01,
        3.06640625e-01, -4.88281250e-02, -9.57031250e-02,  1.99218750e-01,
       -1.57226562e-01, -2.80761719e-02,  1.58203125e-01, -2.42919922e-02,
        1.29882812e-01, -8.98437500e-02, -7.61718750e-02,  3.54003906e-02,
       -3.06396484e-02,  1.52343750e-01,  5.24902344e-02,  1.60980225e-03,
        5.56640625e-02,  

In [ ]:
vec=model['king'] - model['man'] + model['woman']

In [ ]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

### Custom training for Word2Vec(static embedding)

In [ ]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [ ]:
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
story=[]

In [ ]:
for file in os.listdir("/content/data"):
  print(file)

003ssb.txt
002ssb.txt
004ssb.txt
005ssb.txt
001ssb.txt


In [ ]:
f=open("/content/data/001ssb.txt",encoding='unicode_escape')

In [ ]:
corpus=f.read()

In [ ]:
corpus

'A Game Of Thrones \nBook One of A Song of Ice and Fire \nBy George R. R. Martin \nPROLOGUE \n"We should start back," Gared urged as the woods began to grow dark around them. "The wildlings are \ndead." \n"Do the dead frighten you?" Ser Waymar Royce asked with just the hint of a smile. \nGared did not rise to the bait. He was an old man, past fifty, and he had seen the lordlings come and go. \n"Dead is dead," he said. "We have no business with the dead." \n"Are they dead?" Royce asked softly. "What proof have we?" \n"Will saw them," Gared said. "If he says they are dead, that\'s proof enough for me." \nWill had known they would drag him into the quarrel sooner or later. He wished it had been later rather \nthan sooner. "My mother told me that dead men sing no songs," he put in. \n"My wet nurse said the same thing, Will," Royce replied. "Never believe anything you hear at a woman\'s \ntit. There are things to be learned even from the dead." His voice echoed, too loud in the twilit fores

In [ ]:
raw_sentn=sent_tokenize(corpus)

In [ ]:
for i in raw_sentn:
  print(i)

Streaming output truncated to the last 5000 lines.
She bent over the tub, over Drogo in his bath of 
blood, and kissed him lightly on the brow.
"Bring him back to me," she whispered to Mirri Maz Duur 
before she fled.
Outside, the sun was low on the horizon, the sky a bruised red.
The 
Page 476

khalasar had made camp.
Tents and sleeping mats were scattered as far as the eye could see.
A hot 
wind blew.
Jhogo and Aggo were digging a firepit to burn the dead stallion.
A crowd had gathered to 
stare at Dany with hard black eyes, their faces like masks of beaten copper.
She saw Ser Jorah 
Mormont, wearing mail and leather now, sweat beading on his broad, balding forehead.
He pushed his 
way through the Dothraki to Dany's side.
When he saw the scarlet footprints her boots had left on the 
ground, the color seemed to drain from his face.
"What have you done, you little fool?"
he asked 
hoarsely.
"I had to save him."
"We could have fled," he said.
"I would have seen you safe to Asshai, Princ

In [ ]:
for i in raw_sentn:
  print(simple_preprocess(i))

Streaming output truncated to the last 5000 lines.
['her', 'handmaids', 'and', 'the', 'men', 'of', 'her', 'khas', 'came', 'after', 'smiling', 'and', 'jesting', 'among', 'themselves']
['dothraki', 'hooves', 'had', 'torn', 'the', 'earth', 'and', 'trampled', 'the', 'rye', 'and', 'lentils', 'into', 'the', 'ground', 'while', 'arakhs', 'and', 'arrows', 'had', 'sown', 'terrible', 'new', 'crop', 'and', 'watered', 'it', 'with', 'blood']
['dying', 'horses', 'lifted', 'their', 'heads', 'and', 'screamed', 'at', 'her', 'as', 'she', 'rode', 'past']
['wounded', 'men', 'moaned', 'and', 'prayed']
['jaqqa', 'rhan', 'moved', 'among', 'them', 'the', 'mercy', 'men', 'with', 'their', 'heavy', 'axes', 'taking', 'harvest', 'of', 'heads', 'from', 'the', 'dead', 'and', 'dying', 'alike']
['after', 'them', 'would', 'scurry', 'flock', 'of', 'small', 'girls', 'pulling', 'arrows', 'from', 'the', 'corpses', 'to', 'fill', 'their', 'baskets']
['last', 'of', 'all', 'the', 'dogs', 'would', 'come', 'sniffing', 'lean', 'an

In [ ]:
for filename in os.listdir("/content/data"):
  file_path=os.path.join("/content/data",filename)
  with open(file_path,encoding="unicode_escape") as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))


In [ ]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chap

In [ ]:
len(story)

145020

In [ ]:
story[0]

['storm',
 'of',
 'swords',
 'book',
 'three',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george']

In [ ]:
story[7]

['the',
 'dogs',
 'huddled',
 'together',
 'miserably',
 'on',
 'the',
 'riverbank',
 'as',
 'the',
 'wind',
 'snapped',
 'at',
 'them']

In [ ]:
model=gensim.models.Word2Vec(window=10,min_count=5,vector_size=150)

In [ ]:
model.build_vocab(story)

In [ ]:
model.corpus_count

145020

In [ ]:
model.epochs

5

In [ ]:
model.corpus_total_words

1725638

In [ ]:
model.min_count

5

In [ ]:
model.train(story,total_examples=model.corpus_count,epochs=5)

(6483781, 8628190)

In [ ]:
model.wv["king"]

array([ 1.7848037 ,  2.073864  , -1.1409385 , -1.9568851 , -1.2446599 ,
       -2.193592  , -1.2117412 , -1.4562966 , -0.6892155 , -0.5954116 ,
       -1.3386363 ,  2.5560033 ,  0.54871714, -2.1521745 , -3.011075  ,
       -0.44933274, -0.75952464,  1.5162607 , -1.8541565 ,  1.5303571 ,
       -2.0299098 ,  2.3979452 , -1.4463339 , -0.84526676,  1.8684025 ,
        0.34343803,  2.2871666 , -2.695365  , -0.3867096 ,  1.514293  ,
        2.377053  , -1.6191257 , -0.7814649 , -2.8676896 ,  0.7809448 ,
       -2.267621  ,  0.18393677,  0.11596607,  2.5609457 ,  0.6180848 ,
        2.0744538 ,  1.189758  , -0.7374624 ,  1.6359138 ,  1.1316918 ,
        1.4067523 ,  2.0101373 ,  1.2324445 ,  0.5090417 , -2.0045462 ,
       -2.0869455 , -1.1845982 ,  0.7845538 ,  0.19293773,  0.42605647,
       -0.47822618,  0.83110464,  1.4752225 ,  2.545276  ,  1.6053268 ,
        0.9584974 , -2.201956  ,  0.12538521,  1.8113617 , -0.32155952,
        0.03061454, -0.11856635,  1.3051518 , -0.30169204, -0.68

In [ ]:
len(model.wv["king"])

150

In [ ]:
model.wv["man"]

array([-2.1803508e-02,  3.2307255e-01, -1.2507814e+00,  3.7937489e-01,
       -3.7429991e-01,  2.2146962e+00, -2.4713647e-01, -2.7140641e-01,
        1.2714137e+00,  2.3583081e-01, -2.1547840e+00,  1.5519804e+00,
       -3.8210252e-01, -1.8022342e+00, -1.3071942e+00, -2.3478439e-01,
       -3.6819234e-01,  1.1611487e+00, -4.9396676e-01, -1.6337579e-01,
        1.0978726e+00,  1.2862523e+00, -1.5022727e+00, -1.8742603e-01,
        1.6941028e+00, -2.0995119e-01,  4.4267645e-01, -2.3257287e+00,
        1.9440888e-01, -1.6199030e+00,  1.7624476e+00,  1.1001387e+00,
        7.6310027e-01,  1.5223122e-01,  1.1419364e+00,  4.0114209e-01,
       -1.6525697e+00,  1.5696844e-01,  1.5774678e+00, -1.3097000e+00,
        2.5285444e+00, -1.5657870e-01,  4.0007737e-01,  1.8005472e+00,
        1.1850746e+00,  6.7920077e-01, -2.1692342e-01, -5.1253158e-01,
        3.9580971e-01, -3.2318757e+00,  1.0539153e-01, -6.6562027e-01,
        3.5795414e-01,  1.7936180e+00, -4.4939700e-01,  4.8286456e-01,
      

In [ ]:
model.wv["woman"]

array([ 1.50955915e-01,  3.06196749e-01,  1.77689809e-02, -9.22531588e-04,
        3.61135811e-01,  1.00739944e+00,  1.14849731e-01, -3.23700637e-01,
        7.30698645e-01, -4.38493133e-01, -9.17804897e-01,  6.26716137e-01,
       -1.55689621e+00, -7.72663534e-01, -2.54500031e-01, -5.00692129e-01,
       -1.56966090e-01,  1.01224065e+00,  8.85864437e-01,  8.94428909e-01,
        5.72562575e-01,  1.51302922e+00,  3.12751591e-01,  1.10567153e-01,
        9.92331445e-01, -8.61937776e-02, -4.36071962e-01, -2.40886003e-01,
       -1.88149989e-01, -5.48487067e-01,  7.37857401e-01,  1.04886889e+00,
        6.09915376e-01,  1.05572537e-01, -1.10185772e-01,  1.63416844e-02,
       -1.35823750e+00, -1.82621813e+00, -7.93796256e-02, -6.26098156e-01,
        1.90498495e+00,  6.95639014e-01, -6.24278605e-01,  2.70659834e-01,
       -8.81855071e-01, -5.41338205e-01, -5.58175683e-01, -5.23768544e-01,
        9.34929967e-01, -5.24622679e-01,  1.46649098e+00, -7.32321918e-01,
       -1.12764168e+00,  

In [ ]:
model.wv.most_similar("king")

[('baratheon', 0.6866875886917114),
 ('realm', 0.6368722915649414),
 ('prince', 0.6320066452026367),
 ('throne', 0.6050291657447815),
 ('usurper', 0.5955126881599426),
 ('council', 0.5823175311088562),
 ('tourney', 0.5785896182060242),
 ('dragonstone', 0.5626962780952454),
 ('conqueror', 0.5586085915565491),
 ('war', 0.55375736951828)]

In [ ]:
model.wv.most_similar("daenerys")

[('targaryen', 0.7450941205024719),
 ('stormborn', 0.7340261340141296),
 ('viserys', 0.7187343239784241),
 ('myrcella', 0.7187137007713318),
 ('margaery', 0.6788707971572876),
 ('elia', 0.6746646761894226),
 ('rhaegar', 0.6736820340156555),
 ('princess', 0.6677376627922058),
 ('queen', 0.6636425256729126),
 ('doran', 0.6608638167381287)]

In [ ]:
model.wv.most_similar("queen")

[('princess', 0.732577383518219),
 ('margaery', 0.7291548252105713),
 ('daenerys', 0.6636424660682678),
 ('cersei', 0.6395906805992126),
 ('joffrey', 0.639203667640686),
 ('mother', 0.6335662603378296),
 ('prince', 0.6277040839195251),
 ('myrcella', 0.6210615634918213),
 ('sister', 0.6041292548179626),
 ('guidance', 0.6028342843055725)]

In [ ]:
model.wv.most_similar("dhoni")

KeyError: "Key 'dhoni' not present in vocabulary"

In [ ]:
model.wv.doesnt_match(['jon','rikon','arya','robb','sansa','bran'])

'jon'

In [ ]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [ ]:
vectors=model.wv.get_normed_vectors()

In [ ]:
model.wv.get_normed_vectors().shape

(11760, 150)

In [ ]:
y=model.wv.index_to_key

In [ ]:
len(model.wv.index_to_key)

11760

In [ ]:
model.save("word2vec.model")

In [ ]:
model.save("word2vec.bin")

In [ ]:
! gzip word2vec.bin > word2vec.bin.gz

gzip: word2vec.bin.gz already exists; do you wish to overwrite (y or n)? ^C


In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
X=pca.fit_transform(vectors)

In [ ]:
X.shape

(11760, 3)

In [ ]:
import plotly.express as px
fig=px.scatter_3d(X[200:250],x=0,y=1,z=2,color=y[200:250])
fig.show()